# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-02 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FlightBooking', '0005_auto_20170404_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField(default=0, null=True)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlightBooking.Flight')),
            ],
        ),
    ]
