CREATE DATABASE DBlab2;

go

USE DBlab2;

 -----create table

CREATE TABLE CUSTOMER(UID int NOT NULL PRIMARY KEY IDENTITY, USERNAME char(20) NOT NULL, SEX char(2), BYAER int NOT NULL, CITY char(20));




CREATE TABLE LABEL(LID int NOT NULL PRIMARY KEY IDENTITY, LNAME char(20) NOT NULL);


CREATE TABLE MBLOG(BID int NOT NULL PRIMARY KEY IDENTITY, TITLE char(30) NOT NULL, UID int NOT NULL, PYEAR int NOT NULL, PMONTH int NOT NULL, PDAY int NOT NULL, CONT char(200),
                                 FOREIGN KEY (UID) REFERENCES CUSTOMER(UID));


CREATE TABLE B_L(BID int NOT NULL , LID int NOT NULL, PRIMARY KEY (BID , LID),
                               FOREIGN KEY (BID) REFERENCES MBLOG(BID),
                               FOREIGN KEY (LID) REFERENCES LABEL(LID));


CREATE TABLE FOLLOW(UID int NOT NULL ,UIDFLED int NOT NULL, PRIMARY KEY (UID, UIDFLED),
                                  FOREIGN KEY (UID) REFERENCES CUSTOMER (UID));


CREATE TABLE FRIENDS (UID INT NOT NULL, FUID int NOT NULL, PRIMARY KEY(UID,FUID),
                                    FOREIGN KEY (UID) REFERENCES CUSTOMER (UID));


CREATE TABLE SUB (UID int NOT NULL, LID int NOT NULL, PRIMARY KEY (UID, LID),
                                FOREIGN KEY (UID) REFERENCES CUSTOMER (UID),
                                FOREIGN KEY (LID) REFERENCES LABEL (LID));


CREATE TABLE THUMB (UID int NOT NULL, BID int NOT NULL, PRIMARY KEY (UID, BID),
                                  FOREIGN KEY (UID) REFERENCES CUSTOMER (UID),
                                  FOREIGN KEY (BID) REFERENCES MBLOG (BID));


CREATE TABLE toptoday(TYEAR INT NOT NULL, TMONTH INT NOT NULL, TDAY INT NOT NULL, BID INT NOT NULL , TNO INT NOT NULL,
                                    PRIMARY KEY (TYEAR, TMONTH, TDAY, BID),
                                    FOREIGN KEY (BID) REFERENCES MBLOG(BID));


